version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "artific-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rchtds4cci6o"
s3_prefix = "artific-api"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
