# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >
  artific-api

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  getImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getImage.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns questionnaire.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Role: arn:aws:iam::423767207682:role/service-role/myLambdaExecRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /image/{id}
            Method: GET

  getQuestionsFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: src/handlers/getQuestions.handler
        Runtime: nodejs12.x
        MemorySize: 128
        Timeout: 100
        Description: A Lambda function that returns questionnaire.
        Policies:
          # Give Lambda basic execution Permission to the helloFromLambda
          - AWSLambdaBasicExecutionRole
        Events:
          Api:
            Type: Api
            Properties:
              Path: /questions
              Method: GET
  getArConfigFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: src/handlers/getConfig.arConfigHandler
        Runtime: nodejs12.x
        MemorySize: 128
        Timeout: 100
        Description: A Lambda function that returns AR config.
        Policies:
          # Give Lambda basic execution Permission to the helloFromLambda
          - AWSLambdaBasicExecutionRole
        Events:
          Api:
            Type: Api
            Properties:
              Path: /arconfig
              Method: GET
  recommendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/recommend.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns questionnaire.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Role: arn:aws:iam::423767207682:role/service-role/myLambdaExecRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /recommend
            Method: POST
